export interface CountryData {
  name: string;
  flag: string;
  image: string;
  description: string;
  highlights: string[];
  whyStudy: string[];
  topUniversities: string[];
  intakes: string[];
  tuitionFees: string;
  livingCost: string;
  visaSuccess?: string;
  postStudyWork?: string;
  benefits?: string[];
  roadmap?: string[];
  ageRestriction?: string;
}

export const COUNTRIES: CountryData[] = [
  {
    name: 'United Kingdom',
    flag: '🇬🇧',
    image: 'https://images.pexels.com/photos/460672/pexels-photo-460672.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'World-class universities & 2-year post-study work visa',
    highlights: ['Top QS Rankings', '2-Year PSW', 'Rich Culture'],
    whyStudy: [
      'World-renowned universities with rich academic heritage',
      'Shorter course duration (1-year Masters programs)',
      'part Time work during studies 20hrs per week',
      'Post-study work visa for 2 years',
      'Diverse multicultural environment',
      'Gateway to Europe',
      'Scholarships and Bursaries are available', 
      'paid placements and internships available ',
'Possible admission without IELTS',
    ],
    topUniversities: [
      'University of York Durham',
      'University of Leeds',
      'University of Bristol',
      'University of Liverpool',
      
    ],
    intakes: [ 'January & February(Spring Intake) ','April To July(Mid Intake)','September & October(Fall Intake)', ],
    roadmap: [
      'IELTS',
      'University application',
      'Offer letter',
      'CAS request',
      'Prepare and apply for visa',
      'Fly to UK'
    ],
    tuitionFees: '£12,000 per year',
    livingCost: '£10,224/month outside London ,£1,438/month Inside London',
  },
  {
    name: 'United States',
    flag: '🇺🇸',
    image: 'https://images.pexels.com/photos/64271/queen-of-liberty-statue-of-liberty-new-york-liberty-statue-64271.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'Ivy League excellence & OPT opportunities',
    highlights: ['Ivy League', 'STEM OPT 3 Years', 'Innovation Hub'],
    whyStudy: [
      'Home of 5000+ university and colleges with cutting age research and faculty ',
      'High-quality education with top ranking universities',
      'Scholarship opportunity',
      'Access to global job market and internship opportunity through programs',
      'Home of the largest multinational corporation such as Apple, Microsoft and Amazon',
    ],
    topUniversities: [
      'Johns Hopkins University',
      'University of Pennsylvania',
      'University of California, Los Angeles ',
      'Dartmouth university',
      'University of California, Berkeley',
      'Stevens Institute of technology',
    ],
    intakes: ['Fall (August/September)', 'Spring (January)', 'Summer (May)'],
    tuitionFees: '$20000 per year',
    livingCost: ' $34800 annually',
    roadmap:['Consulting with expert',
             'IELTS/TOEFL/SAT/GMAT Prepration',
             'University selection',
             'Apply to university',
             'Arranging required documents',
             'University acceptance letter',
             'Arranging funds',
             'Apply for the I 20',
             'Visa application',
             'USA visa interview process',
             'Received F1 visa',
    ],    
  },
  {
    name: 'Canada',
    flag: '🇨🇦',
    image: 'https://images.pexels.com/photos/417054/pexels-photo-417054.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'Quality education & pathway to PR',
    highlights: ['PR Pathway', '3-Year PGWP', 'Safe & Welcoming'],
    whyStudy: [
      'Affordable tuition fees compared to US and Australia',
      'Pathway to permanent residenc',
      'Safe and inclusive society',
      'Post study work visa for 3 years',
      'Part-time work opportunity on and off campus for 24 hours per week',
    ],
    topUniversities: [
      'University of British Columbia',
      'University of Victoria',
      'Trent university',
      'University of Alberta',
    ],
    intakes: ['September, January and May are main intakes', 'Limited intakes in April, July and October'],
    roadmap: [
      'IELTS/TOEFL/PTE',
      'Application to university',
      'Offer letter from university',
      'Arranging finance',
      'Study permit application visa',
      'Fly to Canada'
    ],
    tuitionFees: 'CAD 20,000/year',
    livingCost: 'CAD 1,600/month',

  },
  {
    name: 'Australia',
    flag: '🇦🇺',
    image: 'https://images.pexels.com/photos/995765/pexels-photo-995765.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'Beautiful campuses & post-study work rights',
    highlights: ['Up to 4 Years PSW', 'High Quality of Life', 'Research Excellence'],
    whyStudy: [
      'High quality of life and excellent weather',
      'World-class education system',
      'Work opportunities while studying (20 hrs/week)',
      'Post-study work rights for 2-4 years',
      'Multicultural society with strong Indian community',
    ],
    topUniversities: [
      'Australian National University',
      'University of Melbourne',
      'University of Sydney',
      'University of New South Wales',
      'University of Queensland',
    ],
    intakes: ['February (Main)', 'July'],
    roadmap: [
      'IELTS/PTE preparation',
      'University application',
      'Offer the acceptance and COE',
      'Financial assessment',
      'Applying for visa and medicals',
      'Visa grant',
      'Fly to Australia'
    ],
    tuitionFees: 'AUD 35,000 /year',
    livingCost: 'AUD 29,710/year',
  },
  {
    name: 'Germany',
    flag: '🇩🇪',
    image: 'https://images.pexels.com/photos/2524368/pexels-photo-2524368.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'Free tuition at public universities & 18-month work visa',
    highlights: ['No Tuition Fees', 'Strong Economy', 'For study work visa opportunities for 18 months'],
    whyStudy: [
      'Affordable cost of education',
      'German education is one of the oldest and the best in the world',
      'International students are allowed to work for 20 hours per week',
      'Average student wage from €12.83',
      'Post study work visa opportunity for 18 months',
      'Germany is a home of many fortune 500 companies such as Audi BMW Bentley motors Limited, Skoda auto and Volkswagen ',
      'Indefinite rights to remain after 5 years working in Germany',
    ],
    topUniversities: [
      'Lancaster University',
      'EU business School Germany',
      'SRH Berlin University of apply scienceThe university of Western Australia Perthy',
      'Constructor university',
    ],
    intakes: ['March and April(Summer)','September and October(Winter)'],
    roadmap: [
      'IELTS/TOEFL/GRE/German language',
      'Application to university',
      'Pay the university fee 1st year complete fee',
      'APS academic evaluation centre for documents verification',
      'For bachelors TestAS aptitude test',
      'Apply for visa',
      'Fly to Germany'
    ],
    tuitionFees: '€16000/year',
    livingCost: '€$12000/month',
  },
  {
    name: 'France',
    flag: '🇫🇷',
    image: 'https://images.pexels.com/photos/2363/france-landmark-lights-night.jpg?auto=compress&cs=tinysrgb&w=800',
    description: 'Affordable education & rich cultural heritage',
    highlights: ['Cultural Excellence', 'Affordable Fees', 'Schengen Access'],
    whyStudy: [
      'Two years of post study work visa but this is acceptable only for RNCP certified programs on completion of master courses',
      'Subsidy on accommodation 30% 50%',
      'No IELTS and TOEFL required for admissions, but having one gives you a positive impact on your visa outcome',
      'Student can work up to 20 hrs and part-time earning is €10 to €12 per hour. Minimum gross wage is €11.65 per hour.',
      'Advantage of visiting other Schengen countries',
      'Free French language courses offered from government organisation',
      'Low transportation expenses',
      'Internship opportunity multinational company',
    ],
    topUniversities: [
      'NEOMA business school ',
      'Karma Business school ',
      'Clermont school of business ',
      'ECE engineering school'
    ],
    intakes: ['January &  February(Summer)','September & October (Winter)'],
    tuitionFees: ' €9000/year',
    livingCost: '€1,000/month',
    roadmap: [
      'No IELTS and TOEFL required',
      'Application to university',
      'Interview from university representative',
      'Pay the tuition fees',
      'Attend an interview with French education advisor',
      'Visa application',
      'Book an appointment with VFS France',
      'Fly to France',
    ],
  },
  {
    name: 'Netherlands',
    flag: '🇳🇱',
    image: 'https://images.pexels.com/photos/208733/pexels-photo-208733.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'English-taught programs & innovative teaching',
    highlights: ['English Programs', 'High Living Standards', 'Internship opportunities in multinational companies'],
    whyStudy: [
      'Education opportunity of the highest standard and multicultural population',
      'One year of bachelors and master program post study work visa',
      'The university of Netherlands charge compatible low tuition fees and offer the master program exclusively taught in English',
      'Students can work up to 16 hours per week typically part-time earning a 10 € to 15 € per hour',
      'Internship opportunities in multinational companies',
    ],
    topUniversities: [
      'University of twente Enschede',
      'Radboud university ',
      'Utrecht University',
      'University of twente through twente pathway college',
      'TIO university of applied sciences',
    ],
    intakes: ['September & October(Winter)', 'February(Summer)'],
    tuitionFees: '€20,000/year',
    livingCost: '€15000/year',
    roadmap:['GMAT and IELTS preparation',
            'Application to university',
            'Offer letter from university',
            'Funds arrangement',
            'Apply temporary visa for entering Netherland',
            'After arriving in Netherlands University will apply for resident permit on behalf of the students',],
  
    
  },
  {
    name: 'Switzerland',
    flag: '🇨🇭',
    image: 'https://images.pexels.com/photos/691668/pexels-photo-691668.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'World-leading research & multilingual environment',
    highlights: ['Top Research', 'Multilingual', 'High Quality Life'],
    whyStudy: [
      'Rank as one of the best place in the world to leave',
      'Well, ordered country with the high standard of living',
      'Excellent education six months study +6 months internships',
      'Switzerland is known for his innovations',
      'Brilliant transport infrastructure easy to travel around',
    ],
    topUniversities: [
      'EU business school ',
      'Geneva business schools',
      'GUON institute of Higher Education',    
      'Swiss hotel management school',
      'Business &hotel management school',
    ],
    intakes: ['February & April'],
    tuitionFees: 'CHF 18000/year',
    livingCost: 'CHF 1,500/month',
    roadmap: [
      'IELTS exam preparation',
      'Application to university',
      'Telephonic interview from some Institute',
      'Receive provisional admission letter',
      'Pay the deposit amount',
      'Receive the confirmed admission letter',
      'Receive visa authorisation',
      'Take an appointment from BFS for Visa stamping',
      'Buy flight tickets',
      'Fly to Switzerland',
    ],
    ageRestriction: 'Profile of age beyond 30 is not accepted due to embassy restriction',
  },
  {
    name: 'Sweden',
    flag: '🇸🇪',
    image: 'https://images.pexels.com/photos/1098365/pexels-photo-1098365.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'Innovation hub & high quality of life',
    highlights: ['Innovation Focus', 'English Programs', 'Work-Life Balance'],
    whyStudy: [
      'It is clean and safe and high standard of living',
      'It’s rang among the world, most innovative nation',
      'Not requirement of learning Swedish language for the admission',
      'Unlimited part-time work rights for international students students can earn between €10-€13',
      'Post study work visa for 1 year',
      'No age restriction for study application',
      'Sweden is based on many Renowned companies',
    ],
    topUniversities: [
      'Halmsted university ',
      'Linnaeus university',
      'Jonkoping university ',
      'Dalarna university',
      'Kristiansted university',
    ],
    intakes: ['August/September (Fall)', 'January (Spring)'],
    tuitionFees: 'SEK 1,15000/year',
    livingCost: 'SEK 11,214/month',
    roadmap: [
      'IELTS and GRE preparation (some courses)',
      'Application to university',
      'Receive an offer letter from university',
      'Arrange funds',
      'Apply to Visa',
      'Interview at Embassy',
      'Visa received',
      'Fly to Sweden',
    ],
  },
  {
    name: 'New Zealand',
    flag: '🇳🇿',
    image: 'https://images.pexels.com/photos/1647220/pexels-photo-1647220.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'World-class education & stunning natural beauty',
    highlights: ['3-Year Post-Study Work', 'Safe Environment', 'Adventure Hub'],
    whyStudy: [
      'Warm and welcome involvement',
      'Universities rank under top 500 in QS world ranking',
      'New Zealand is one of the fourth most peaceful country in the world',
      'Student can work 20 hours per week and 40 hours during holidays student can earn between NZD 23.15 per hour',
      'A 3 years of post study work visa',
      'Permanent residency opportunity',
      'Dependent allowed',
    ],
    topUniversities: [
      'University of Auckland',
      'University of Otago',
      'Victoria University of Wellington',
      'University of Canterbury  Christchurch ',
      'University of Waikato Hamilton',
    ],
    intakes: ['February (Main)', 'July'],
    tuitionFees: 'NZD 26167/year',
    livingCost: 'NZD 19260/month',
  },
  {
    name: 'Dubai',
    flag: '🇦🇪',
    image: 'https://images.pexels.com/photos/1534560/pexels-photo-1534560.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'Global business hub & world-class education',
    highlights: ['Tax-Free Living', 'Global Business Hub', 'Luxury Lifestyle'],
    whyStudy: [
      'Attracting different nationalities',
      'Shorter than more intensive courses',
      'UK Australian US university have their campus in Dubai',
      'Student can take transfer to the balance campus after finishing one academic year of their UG courses based on their scores',
      'Gap Student is also acceptable',
      'Options without IELTS is also available',
      'Whose graduate students can legally change their student visa to work visa in case if they find employer',
    
    ],
    topUniversities: [
      'University of Birmingham Dubai campus',
      'Hult International business school Dubai campus',
      'Middlesex University Dubai',
      'Abu Dhabi University',
      'Manipal University Dubai campus',
    ],
    intakes: ['September (Fall)', 'January (Spring)'],
    tuitionFees: 'INR 50000/year',
    livingCost: 'INR 740000/month',
    roadmap: [
      'IELTS if required',
      'Application to university',
      'Paying university deposit',
      'Apply for Visa',
      'Receive entry clearance visa for Dubai',
      'Student get the guaranteed visa at the Visa office of the Dubai airport',
    ],
  },
  {
    name: 'Ireland',
    flag: '🇮🇪',
    image: 'https://images.pexels.com/photos/3566187/pexels-photo-3566187.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'European education excellence & tech industry',
    highlights: ['2-Year Stay Back', 'EU Access', 'Tech Hub'],
    whyStudy: [
      'World class universities',
      'Low cost tuition fees and accommodation',
      'Masters degree of one year',
      'Post study work visa for two years after masters',
      'Post study work visa for one year for bachelors',
      'Chance to get infinite right to stay permanent residency',
      'Friendly and safe country',
      'Scholarship and student grants are available'
    ],
    topUniversities: [
      'Trinity College Dublin',
      'University College Dublin',
      'National University of Ireland, Galway',
      'University College Cork',
      'Dublin City University',
    ],
    intakes: ['September (Main)'],
    roadmap: [
      'IELTS/TOEFL/PTE/DET preparation',
      'Apply to university',
      'Offer letter',
      'Arrange finance',
      'Apply for visa',
      'Flight to Ireland'
    ],
    tuitionFees: '€14,000/year',
    livingCost: '€12,000/month',
    visaSuccess: '93%',
    postStudyWork: '2 years (Stamp 1G visa)',
    benefits: ['EU Member', 'English Speaking', 'Tech Industry Hub'],
  },
  {
    name: 'Spain',
    flag: '🇪🇸',
    image: 'https://images.pexels.com/photos/1388030/pexels-photo-1388030.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'Rich culture & affordable European education',
    highlights: ['Cultural Heritage', 'Affordable Fees', 'Warm Climate'],
    whyStudy: [
      'It has the fifth largest economy in the European',
      'Post study work visa up to 2 years',
      'Low tuition fees',
      'No IELTS and TOEFL exam required ',
      'Part-time jobs work up to 30 hours per week and typically part-time earning is €8 to €10 per hour',
      'Internship opportunities in multinational companies available',
    ],
    topUniversities: [
      'University of Barcelona',
      'Autonomous University of Madrid',
      'Complutense University of Madrid',
      'University of Valencia',
      'Pompeu Fabra University',
    ],
    intakes: ['September-October(Main)', 'January-February'],
    tuitionFees: '€1,000/year',
    livingCost: ' €13,000/year',
    roadmap: [
      'IELTS required for some universities',
      'Application to university',
      'Attend Skype interview from university representative',
      'Arrange finance and health insurance',
      'Apply for Visa',
      'Schedule appointment with embassy',
      'Receive Visa',
      'Fly to Spain',
    ],
  },
  {
    name: 'Italy',
    flag: '🇮🇹',
    image: 'https://images.pexels.com/photos/2363/france-landmark-lights-night.jpg?auto=compress&cs=tinysrgb&w=800',
    description: 'Historic universities & art capital of the world',
    highlights: ['Historic Universities', 'Art & Design', 'Cultural Heritage'],
    whyStudy: [
      'Quality education',
      'Part-time job opportunities when can work up to 20 hours a week earning arranged from €7 to €15 per hour',
      'Easy access to Schengen countries',
      'Most Italian university of English taught master program',
      'PSW for 1 year',
      'Employment rate of recent graduate is increased from 84.3%',
      'Internship opportunities in multinational companies',
    ],
    topUniversities: [
      'University of Padua',
      'LUISS Guido Carli',
      'Guglielmo Marconi University ',
      'Istituto Marangoniiversity of Padua',
      
    ],
    intakes: ['September (Main)', 'February'],
    tuitionFees: '€3000/year',
    livingCost: '€6947/month',
  },
  {
    name: 'Finland',
    flag: '🇫🇮',
    image: 'https://images.pexels.com/photos/1770809/pexels-photo-1770809.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'Nordic excellence & innovation-driven education',
    highlights: ['High Quality', 'Innovation Focus', 'Safe Environment'],
    whyStudy: [
      'World class and modern education',
      'Scholarships are available for International student 50 % to 100%',
      'English is a taught for bachelors and masters',
      'One of the safest and cleanest countries in the world',
      'Country known for is innovator scoring high in technology R&D and manufacturing',
      'Two years post study work visa available after bachelors and masters',
      'Students can work up to 30 hours per week part-time but can only allow to do such a job that related to their study course',
      'Typically wage range for part-time job is €9 to €15 per hour Student who speak finnish ',
      'Language skills gets higher wages as compared to someone who have no skill',
    ],
    topUniversities: [
      'LUT university Lappeenranta',
      'LAB university of applied science',
      'Aalto university ',
      'University of Vaasa',
    ],
    intakes: ['September (Main)', 'January'],
    tuitionFees: '€9500/year',
    livingCost: '€9600/month',
  },
  {
    name: 'Russia',
    flag: '🇷🇺',
    image: 'https://images.pexels.com/photos/753339/pexels-photo-753339.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'Affordable education & rich academic tradition',
    highlights: ['Affordable Fees', 'Rich History', 'Technical Excellence'],
    whyStudy: [
      'Russia is well established education system recognise for his high literacy rates and quality',
      'Many universities offer courses in English language reducing the barrier for international students',
      'Tuition fees of Russia is relatively low has compared to other western countries',
      'PSW for 1 year ',
      'Part-time work for 20 hours per week',
    ],
    topUniversities: [
      'Synergy university of Moscow',
      'National research nuclear university (MEPhI)',
    ],
    intakes: ['September (Main)'],
    tuitionFees: 'RUB 552991/year',
    livingCost: 'RUB30000/year',
    roadmap: [
      'Course selection (only specific courses available in medicine and engineering)',
      'Application to university',
      'Online interview from university',
      'Gathering all finances plus health insurance',
      'Applying for Visa at Embassy',
      'Fly to Russia',
    ],
  },
  {
    name: 'Malta',
    flag: '🇲🇹',
    image: 'https://images.pexels.com/photos/2166559/pexels-photo-2166559.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'English-speaking EU member & Mediterranean lifestyle',
    highlights: ['English Speaking', 'EU Member', 'Island Lifestyle'],
    whyStudy: [
      'Recognise program',
      '7200% fee refunds to tax credit short courses comparatively lower fees',
      'Earn while you learn 20 hours part-time job no to racism safest in the world for foreigners',
      '1 resident car 26 engine nations to explore',
      
    ],
    topUniversities: [
      'College of de Paris Malta',
      'Global business school Malta',
      'Global College Malta',
      'Queens University of London Malta',
    ],
    intakes: ['September & October (Fall)', 'January & February(Spring)'],
    tuitionFees: '€6656.27/year',
    livingCost: '€13000/month',
    roadmap: [
      'IELTS if required',
      'Application to university',
      'Interview from university representative',
      'Offer from university',
      'Payment of tuition fees',
      'Arrange documentation for visa including book flight tickets',
      'Interview at Visa embassy',
      'Receive Visa',
      'Fly to Malta',
    ],
  },
];

export const COUNTRY_NAMES = COUNTRIES.map(country => country.name);
